### ISSUE TITLE
Migrate Tekton single arch image build to ghcr.io

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#2221] opened 2024-10-02 11:26 UTC
### Feature request

Migrate the [single-arch-template](https://github.com/tektoncd/plumbing/blob/main/tekton/resources/images/single-arch-template.yaml) pipeline to publish to ghcr.io. This includes updates to any of the [cronjobs](https://github.com/tektoncd/plumbing/tree/main/tekton/cronjobs/dogfooding/images) that use this template to build images.

**Note**: To be implemented as a separate PR: update references in the `plumbing` repo from gcr.io to ghcr.io once the new images are produced.

The pipeline project [release pipeline](https://github.com/tektoncd/pipeline/blob/main/tekton/publish.yaml). has been migrated and can provide some insight. 

Some key information for the migration:
- Existing path: `gcr.io/tekton-releases/dogfooding/<image-name>`
- Target path: `ghcr.io/tektoncd/plumbing/<image-name>`
- [GitHub requires OCI labels](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images) to be set to associate images with the correct GitHub repo, which should be implemented in #2222 

### Use case

Reduce Cloud Storage / Container Registry Spending: https://github.com/tektoncd/plumbing/issues/2157

### Additional Info

- the template part defines the pipeline that is executed to build images
- the cronjobs provide the trigger for the execution of the pipelines, and they include the list of parameters as well as the frequency of execution

The template part needs to be updated so that it may work with ghcr.io. The current version works with gcr.io, and unfortunately, it's not enough to change the target registry as authentication works a bit different (for gcr.io we used a service account file, and for ghcr.io we use a PAT), and ghcr.io requires OCI labels to be set

There are three types of builds we do today, which correspond to three separate templates. 

* Single architecture: https://github.com/tektoncd/plumbing/issues/2221, PLATFORMS and BUILD_TYPE are not set in the cronjob
* Multi-architecture, using docker: https://github.com/tektoncd/plumbing/issues/2223, PLATFORMS is set and BUILD_TYPE=docker
* Multi-architecture, using ko: https://github.com/tektoncd/plumbing/issues/2224, PLATFORMS is set and BUILD_TYPE=ko

This issue covers updating the template and cronjob for single architecture.

The order of implementation should be:

- Set the OCI labels in Dockerfiles https://github.com/tektoncd/plumbing/issues/2222
- Adapt the template to work with ghcr.io (see the changes in the pipeline project [release pipeline](https://github.com/tektoncd/pipeline/blob/main/tekton/publish.yaml) for inspiration)
- Adapt the cronjobs (this can be in the same PR as the template or separate)

**Comment by LiteBrick204** [comment] 2024-11-05 09:35
I would like to work on this

**Comment by afrittoli** [comment] 2024-11-05 09:43
The username for ghcr.io is `tekton-robot` (same as https://github.com/tektoncd/plumbing/blob/eee5180f5a9a5a4d9a7491dd1adc924bababf2db/tekton/cronjobs/dogfooding/releases/pipeline-nightly/cronjob.yaml#L24C24-L24C36).
The credentials are defined in a secret available on the cluster, called `ghcr-creds` (same as https://github.com/tektoncd/plumbing/blob/eee5180f5a9a5a4d9a7491dd1adc924bababf2db/tekton/resources/nightly-release/overlays/pipeline/template.yaml#L51-L52)

**Comment by AlanGreene** [comment] 2024-11-26 14:39
Looks like the CronJob update was merged prematurely and nightly releases have been failing since.

PR open to update the template to use the correct credentials for publishing to ghcr.io: https://github.com/tektoncd/plumbing/pull/2323

**Comment by afrittoli** [comment] 2024-11-26 15:18
Thanks @AlanGreene, yes, we're aware of this (cc @vdemeester), and decided that for now we would `crane cp` the images and then fix the builds, @LiteBrick204 has been working on this. 
@AlanGreene your help is greatly appreciated - it would be good to sync with @LiteBrick204 to make sure you're not working on the same PRs.

**Comment by AlanGreene** [comment] 2024-11-26 15:57
@LiteBrick204 let me know if you're still working on this. I have a PR open to fix the single arch builds, but haven't looked at multi-arch or ko-multi-arch yet.

**Comment by AlanGreene** [comment] 2024-11-28 12:30
/reopen

Most of the single arch builds are passing now:
![image](https://github.com/user-attachments/assets/dbf2fb9e-d604-4b85-90e3-693fb791471e)

I've removed the `openssh-server` cronjob as that image was removed from the plumbing repo and no longer needs to be built.

`catlin` is failing due to a python issues in its Dockerfile, issue open to track: https://github.com/tektoncd/catlin/issues/60

That leaves `kubectl` and `ko-gcloud` which are both failing with the following error:
`2024-11-28T12:15:55.480380452Z kaniko should only be run inside of a container, run with the --force flag if you are sure you want to continue`

Not sure why these 2 are behaving differently from the others…

**Comment by AlanGreene** [comment] 2024-11-28 12:34
Confirmed that adding the `--force` flag allows the task to continue successfully, but it shouldn't be necessary. The same pipeline is used for the other single arch images and they don't encounter this problem.

**Comment by AlanGreene** [comment] 2024-11-29 10:11
All passing with latest change, except for `catlin` which is tracked separately. Closing

**Closed by AlanGreene** 2024-11-29 10:11 UTC
Labels: kind/feature, Hacktoberfest
