### ISSUE TITLE
The check-pr-has-kind-label check is stuck

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/plumbing#979] opened 2021-12-27 16:48 UTC
This seems to have been stuck for 1-2 weeks now.

There are a few PRs in pipelines with no results here:
* https://github.com/tektoncd/pipeline/pull/4437
* https://github.com/tektoncd/pipeline/pull/4439
* https://github.com/tektoncd/pipeline/pull/4434

I've kicked a few of these to no avail.

Might be related to https://github.com/tektoncd/plumbing/issues/945

Should we consider moving this check to optional?

**Comment by afrittoli** [comment] 2022-01-04 17:46
Thanks @dlorenc for reporting this and sorry about the incovenience!
This should be fixed by https://github.com/tektoncd/plumbing/pull/970

**Comment by dibyom** [comment] 2022-01-04 17:53
> Might be related to #945

Just checked recent deliveries of the webhooks and did not find any 404s

> Should we consider moving this check to optional?

+1

@afrittoli do you think moving the implementation to a custom task will help with the race condition issues?

**Comment by afrittoli** [comment] 2022-01-04 17:57
@dibyom yes, it might.  We could also deploy different solutions in parallel, for instance used by different repos.
The issue that happened recently was caused by name being too long, which should be fixed by the latest iteration of the PR.

**Closed** 2022-06-03 19:24 UTC
Labels: kind/bug, lifecycle/rotten
