### ISSUE TITLE
Setup peribolos for tektoncd org management

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/plumbing#109] opened 2019-11-04 14:07 UTC
Currently adding users to the tektoncd org is manual. We should automate this using something like peribolos: https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos

Plan:

- Add a peribolos config to the tektoncd/community github repo
- Add documentation for users on how to add themselves
- Run this manually for now
- Wrap peribolos in a tekton Task
- Automate the peribolos syncing

**Comment by bobcatfish** [comment] 2019-11-04 14:28
Duplicate of https://github.com/tektoncd/community/issues/30. Closing, unless we think plumbing is a better place for this issue?

**Closed by bobcatfish** 2019-11-04 14:28 UTC

**Comment by dlorenc** [comment] 2019-11-04 14:33
Ah, good point. I think we need some code in both places, but I'll track it there.
